### ISSUE TITLE
Ошибка при открытии BDDEditor.epf в конфигурации с установленным режимом совместимости "Версия 8.3.5"

### ISSUE THREAD

**Issue by sergpogo** [silverbulleters/vanessa-bdd-editor#103]
```Gherkin
Функционал: Использование обработки BDDEditor.epf
   Как участник курса промышленных стандартов разработки на 1С
   Я хочу пользоваться обработкой BDDEditor.epf

Сценарий: ОткрытиеBDDEditor.epf
  Допустим: У меня есть конфигурация с установленным режимом совместимости Версия 8.3.5
  Когда: я открываю обработку BDDEditor.epf
  Тогда: я получаю список ошибок
```
![errors](https://cloud.githubusercontent.com/assets/15350381/17944246/94c75c94-6a47-11e6-97a9-e7858e992b97.PNG)

**Comment by nixel2007** [comment]
В данный момент работа поддерживается только с версии 8.3.6 и выше.

Но из возможностей 8.3.6 в коде используются только новые строковые функции, т.е. это не сложно поменять руками. Надеюсь, @Hissin меня поправит, если это не так.

**Comment by nixel2007** [comment]
>  Как участник курса промышленных стандартов разработки на 1С

отдельно добавлю, что для работы с vanessa-behavior рекомендуется использовать платформу 8.3.7,а лучше 8.3.8, т.к. там более стабильно работает механизм автоматизированного тестирования 1С

**Comment by sergpogo** [comment]
Тогда, наверное, нужно описать это  **README.md** и закрыть этот запрос.

**Comment by alehinsasha** [comment]
@sergpogo README - дополнил, issue - закрываю.
