### ISSUE TITLE
Необходимо подключить фича ридер из проекта vanessa-behavior

### ISSUE THREAD

**Issue by Pr-Mex** [silverbulleters/vanessa-bdd-editor#2]
Вот здесь https://github.com/silverbulleters/vanessa-behavoir
есть обработка vbFeatureReader.epf, которая может парсить фичи и отдавать прочитанное дерево значений.

**Comment by Hissin** [comment]
Сейчас вызов ведется бехевора. Будет переписано на ридер? или так и оставлять?

**Comment by allustin** [comment]
пока используем vbFeatureReader - для ускорения
а в перспективе будем выносить часть библиотечных обработок в отдельный модуль.

главное перед рефакторингом покрыть сценариями поведения текущий функционал, тогда будет не страшно рефакторить

**Comment by Hissin** [comment]
Ок. как доделаю создание и редактирование перепишу на vbFeatureReader с behavior. 
Между тем и другим напишу фичи

**Comment by Hissin** [comment]
пока не перенесена функциональность из ридера в бихевор оставила бихевор. осталось разобрать дерево по задаче

**Comment by Pr-Mex** [comment]
Вынесем ридер отдельно когда согласуем новую архитектуру и API.

**Comment by Hissin** [comment]
Сделала заполнение без поддержки асинхронности. Осталось сделать заполнение с поддержкой асинхронности

**Comment by allustin** [comment]
@Hissin могу закрыть или нужно брать в план

**Comment by Hissin** [comment]
@allustin - Новый ишуз будет на рефакторинг в связи с выпуском commons. 
Закрываю пока текущую задачу
