### ISSUE TITLE
Сформировать и отправить письмо заказчику с корректировкой требований

### ISSUE THREAD

**Issue by Hissin** [silverbulleters/vanessa-bdd-editor#31]
Сформировать и отправить письмо заказчику с корректировкой требований

**Comment by Hissin** [comment]
Где брать параметры подключения почты?

**Comment by Hissin** [comment]
Во всех ли конфигурациях одинаковые метаданные по настройке учетной записи почты

**Comment by alehinsasha** [comment]
БСП!

**Comment by Hissin** [comment]
ага) только вот есть самописные... все равно надо будет выносить в параметры. надо придумать как это красиво сделать

**Comment by allustin** [comment]
@Hissin всё просто

mailto:?subject=Тема сообщения&body=Здравствуй, уважаемый заказчик. Нам необходимо у тебя уточнить

Де факто метод в 1С ЗапуститьПриложение или что-то подобное

**Comment by Hissin** [comment]
@allustin  Т.е. не формировать текст на основании изменений? а просто шаблонно текстовка в письмо и вложенный файл?

**Comment by allustin** [comment]
~~~
[InternetShortcut]
URL=mailto:?subject=Тема сообщения&body=Здравствуй, уважаемый заказчик. Нам необходимо у тебя уточнить
WorkingDirectory=C:\WINDOWS\
ShowCommand=7
IconIndex=1
IconFile=C:\WINDOWS\SYSTEM\url.dll
Modified=20F06BA06D07BD014D
HotKey=1601
~~~

прям просто временный файл URL - который фактически откроет почтовик и вставит туда текст письма ;-)

**Comment by Hissin** [comment]
@allustin  Я это понимаю. Просто я хотела сделать подкомменты прямо с редактора, чтобы еще было дополнения для понимания.

**Comment by Hissin** [comment]
@allustin в смысле когда я набираю изменения в тексте фичи комментить почему я это сделала. И вставить в текст письма мои комменты с ссылкой на корректируемую строку во вложенном файле

**Comment by Hissin** [comment]
@allustin Так сойдет? 	
	ТекстСообщения = СтрЗаменить(ТекстПисьма, Символы.ПС, "%0D");
	Команда = "mailto:<" + СокрЛП(ЭлАдресЗаказчика) + ">?subject=" + Тема + "&body=" + ТекстСообщения;
	WshShell = Новый COMObject("WScript.Shell");
	WshShell.Run("""" + Команда + """");

**Comment by Hissin** [comment]
похоже есть минус. с вложением файла

**Comment by Hissin** [comment]
Кто шарит в пхп или яве?:)

**Comment by alehinsasha** [comment]
в 1С создай (Новый → HTML документ) у него три закладки. На закладке
"Редактирование" пишешь текст, на закладке "Текст" смотришь HTML код)))

2015-12-04 0:21 GMT+03:00 Hissin <notifications@github.com>:

**Comment by Hissin** [comment]
@alehinsasha  нее, я про то, чтобы файл вложить. Текст то я умею редактировать

**Comment by Hissin** [comment]
как вариант использовать OutlookApplication...

**Comment by Hissin** [comment]
http://php-include.ru/stati/otpravka-e-mail-s-vlozheniem

**Comment by Hissin** [comment]
как обойти разрешение аутлука?

**Comment by Hissin** [comment]
http://www.forum.mista.ru/topic.php?id=272814

**Comment by Hissin** [comment]
Как быть с linux?

**Comment by Hissin** [comment]
Пока оставляю как есть. На будущее #38. и Все вытекающие из него.
