### ISSUE TITLE
Ошибка при подключении каталога инструментов

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-bdd-editor#53]
![2016-01-14_8-59-17](https://cloud.githubusercontent.com/assets/8247178/12316928/36697b14-ba9d-11e5-82a4-5339f4bb34ac.png)

**Comment by Hissin** [comment]
@alehinsasha - выключи пока асинхронность. Ошибку убрала, но еще не дописала код для подстановки в асинхронном режиме.
