### ISSUE TITLE
Ошибка при загрузке feature-файла

### ISSUE THREAD

**Issue by alehinsasha** [silverbulleters/vanessa-bdd-editor#54]
Открываю эдитор → Жму кнопку "Загрузить фича-файл" → Ошибка

![2016-01-16_8-39-14](https://cloud.githubusercontent.com/assets/8247178/12370723/d6b9a798-bc2c-11e5-8636-bf569313913b.png)

**Comment by Hissin** [comment]
@alehinsasha не указаны пути к Behavior и каталогу инструментов.

**Comment by Hissin** [comment]
никак не удается воспроизвести такую ошибку...

**Comment by purtcer** [comment]
Вот немного другое описание. Ситуация та же, пути не прописаны к каталогу BDD editor и обработке поведения, в результате ошибка:
![image](https://cloud.githubusercontent.com/assets/12675941/12918005/c04d5ce6-cf4d-11e5-9680-07143e8a305c.png)

**Comment by Hissin** [comment]
@purtcer  покажи скрин с настройками параметров. ошибка из-за неправильно настроенных путей

**Comment by Hissin** [comment]
@purtcer  спасибо. добавлю проверку на заполненность реквизитов, чтобы в дальнейшем вопросов не возникало.
