### ISSUE TITLE
Добавлять перенос строки в конец генерируемого фиче-файла

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/vanessa-bdd-editor#57]
На самом деле это касается всех генерируемых файлов, хранимых под гитом, но в последнем видео про бдд эдитор это прямо в глаза бросилось :)

**Comment by Hissin** [comment]
@nixel2007 не совсем поняла что именно необходимо? в конец шаблога добавить перенос на новую строку для написания? Или когда открывается фича-файлы активизировать нижнюю строку? напиши сценарий поведения

**Comment by nixel2007** [comment]
@Hissin Да, именно в конец шаблона фичи добавить перенос на новую строку.
Причина - вставка символа переноса расценивается гитом как изменение самой строки.

Т.е. если в сгенерированную фичу https://github.com/silverbulleters/vanessa-behavior/commit/d10f17b11c8b4ee1786c9ac4581d2693c7a20117#diff-cd0e97d9a3fb460d6d763fb75301bab9R27 добавить еще одну строку, в гите отобразится  добавленная строка как собственно добавление, и строка с переносом как изменение.

**Comment by nixel2007** [comment]
В терминах bdd будет как-то вот так... (простите меня за косноязычность)
Использовал часть имеющейся фичи:

```gherkin
	Когда В открытой форме я нажимаю на кнопку с заголовком "Создать фичи по шаблону"
	И 	  В открытой форме в поле "СтруктураДляЗагрузки" заполнено значение
	Тогда создается фича-файл во временном каталоге Temp в каталоге "СтруктураДляЗагрузки"
	И файле последняя строка пустая
```

Если описать "кто/что/зачем", то:
```gherkin
	Как разработчик
	Я хочу быть уверенным, что последняя строка фиче-файла является пустой строкой
	Чтобы исключить лишние отличия при просмотре изменений в коммите
```

Надеюсь, мысль понятна.

**Comment by Hissin** [comment]
@nixel2007 понятно. Хорошо. Завтра добавлю.
