### ISSUE TITLE
Не обновляется Каталог feature-файлов при открытии

### ISSUE THREAD

**Issue by purtcer** [silverbulleters/vanessa-bdd-editor#91]
> Заполните шаблон обсуждения GIT (GitHub, GitLab, Vanessa Hub)

```Gherkin
Функционал: Обновлять каталог feature-файлов
   Как аналитик
   Я хочу чтобы при повторном открытии обработки заполнялся список каталог feature-файлов
Сценарий: заполнение списка каталог feature-файлов
  Когда: открываю обработку VBD
  И структура хранения требований заполнена 
  И Источник выбран Структура каталогов
  Тогда: каталог feature-файлов обновляется автоматически
```
Сейчас для его обновления необходимо перевыбрать каталог структуры хранения требований. Если при открытии попытаться раскрыть список, он очищается.
![image](https://cloud.githubusercontent.com/assets/12675941/14013071/2baf6b48-f1bb-11e5-8e17-be2707509c29.png)

**Comment by Hissin** [comment]
Не удалось воспроизвести ошибку. Какая версия обработки используется? И какие настройки конфигурации?

**Comment by Hissin** [comment]
@purtcer Никак не удается воспроизвести ошибку. В каком режиме у тебя конфигурация? Синхронность/модальность/платформа

**Comment by purtcer** [comment]
[Project001.zip](https://github.com/silverbulleters/vanessa-bdd-editor/files/193566/Project001.zip)
В архиве видео

**Comment by Hissin** [comment]
@purtcer теперь понятно в чем проблема. Я поставила проверку при открытии, что окончанием пути к структуре является каталог features. 
Причина: Когда случайно выбираешь не тот каталог производится поиск по всем вложенным каталогам, если вложенность большая это будет долго, вплоть до вылета (один раз таки напоролась на такой исход). При этом оставила обходной маневр в плане выбора каталога и заполнения таки вручную, а не при открытии. Просто для удобства все используют именно единое наименование каталога features, а уже внутри всё разбивается по компонентам. 
Варианты решения:
1. Создать каталог features и таки хранить внутри него все фича-файлы в разрезе любых компонент
2. Убрать "защиту" при открытии как обходной маневр при случайном выборе неверного каталога
3. Добавить параметр для индивидуальной настройки использования/не использования каталога features

Какой тебе более удобен? Конечно я сделаю третий в том числе, но думаю и первый вариант тебе стоит рассмотреть.

**Comment by purtcer** [comment]
Мне первого варианта достаточно. Завтра попробую. Спасибо. А об этом написано где-то? Я, правда, не особо искал.

**Comment by Hissin** [comment]
@purtcer это пока не оговорено явно. Скорее всего из-за того, что ты первый такой :) Т.к. пока что все использовали bootstrap или же изначально создавали features, как единый и понятный. Учтем и примем меры :)

**Comment by purtcer** [comment]
Видео по обновлению фич
[Project002.zip](https://github.com/silverbulleters/vanessa-bdd-editor/files/199206/Project002.zip)

**Comment by Hissin** [comment]
@purtcer видимо это было изначально мной задумано :) не помню почему. Добавила обновление при смене каталога.
