### ISSUE TITLE
Ошибка парсинга "Функциональность"

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/vanessa-bdd-editor#93]
@Hissin Прости меня ради бога)

```Gherkin
Функциональность: Открытие feature-файлов в bdd-editor
   Как пользователь BDD Editor
   Я хочу писать файлы по-правильному ;)
 
Сценарий: Открытие фиче-файла
  Допустим: Есть фича-файл "Сложение" с разделом "Функциональность"
  Когда: Я открываю фича-файл в bdd-editor
  Тогда: фича загружается корректно
  И в Список feature-файлов есть фича "Сложение"
```

Текущее поведение:
![default](https://cloud.githubusercontent.com/assets/1132840/14061271/26305032-f38d-11e5-9e58-5c48c47b4fea.PNG)

**Comment by Hissin** [comment]
@nixel2007 :) жду инструментария по парсингу просто, поэтому не переписывала ручной. Но раз уже требуется, поправлю в ближайшем релизе

**Comment by Hissin** [comment]
@nixel2007 добавила функциональность. Сейчас добавлю еще и остальные ключевые слова
