### ISSUE TITLE
ЭтотОбъект

### ISSUE THREAD

**Issue by vsuh** [silverbulleters/vanessa-bdd-editor#96]
Это только у меня не работает?
![image](https://cloud.githubusercontent.com/assets/12156293/15425995/60f186dc-1e94-11e6-8a43-9e3cef5ca4cf.png)
1С:Предприятие 8.3 (8.3.7.2008)  Управление автотранспортом Стандарт, редакция 1.0 (yat_01.01) (1.0.11.1)
Copyright © ООО "1C", 2012. Все права защищены
(http://www.1c.ru)

**Comment by JohnyDeath** [comment]
Режим совместимости какой?

**Comment by vsuh** [comment]
![image](https://cloud.githubusercontent.com/assets/12156293/15430712/2f33cd10-1eaf-11e6-9627-ac947fa2df79.png)

**Comment by JohnyDeath** [comment]
В этом и проблема. "ЭтотОбъект" для формы появился чуть позже. Надо переводить режим совместимости на что-нибудь посвежее

**Comment by vsuh** [comment]
Т.е., если перевести "на посвежее" нельзя, значит, каюк?

**Comment by JohnyDeath** [comment]
Есть конечно вариант попробовать переписать эти места самому. Конкретно в этом случае заменить на "ЭтаФорма", но будет ли работать все остальное - не известно, надо проверять
А вообще бехавиор тоже использует довольно-таки активно последние плюшки платформы. Т.е. желательно бы соскочить с такой совместимости.

**Comment by Hissin** [comment]
@vsuh как вариант, просто рядом положить чистую конфигурацию без совместимости. Тогда проблем не будет. не обязательно использовать в рабочей базе обработку.
